adlist.o: adlist.c adlist.h zmalloc.h
ae.o: ae.c ae.h zmalloc.h config.h ae_kqueue.c ae_epoll.c ae_select.c ae_evport.c
ae_epoll.o: ae_epoll.c
ae_evport.o: ae_evport.c
ae_kqueue.o: ae_kqueue.c
ae_select.o: ae_select.c
bitops.o: bitops.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h
config.o: config.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h \
 
crc16.o: crc16.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h
crc64.o: crc64.c
db.o: db.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h \
 
debug.o: debug.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h \
 
dict.o: dict.c fmacros.h dict.h zmalloc.h redisassert.h
endianconv.o: endianconv.c
geo.o: geo.c geo.h server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h  ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h \
 ../deps/geohash-int/geohash_helper.h ../deps/geohash-int/geohash.h
hyperloglog.o: hyperloglog.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h  ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h
intset.o: intset.c intset.h zmalloc.h endianconv.h config.h
latency.o: latency.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h  ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h
lzf_c.o: lzf_c.c lzfP.h
lzf_d.o: lzf_d.c lzfP.h
memtest.o: memtest.c config.h
multi.o: multi.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h  ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h
notify.o: notify.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h  ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h
object.o: object.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h  ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h
pqsort.o: pqsort.c
pubsub.o: pubsub.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h  ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h
quicklist.o: quicklist.c quicklist.h zmalloc.h ziplist.h util.h sds.h \
 lzf.h
rand.o: rand.c
release.o: release.c release.h version.h crc64.h
rio.o: rio.c fmacros.h rio.h sds.h util.h crc64.h config.h server.h \
 solarisfixes.h ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h \
 dict.h adlist.h zmalloc.h  ziplist.h intset.h version.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h
scripting.o: scripting.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h  ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h \
 rand.h  ../deps/lua/src/lauxlib.h ../deps/lua/src/lua.h \
 ../deps/lua/src/lualib.h
sds.o: sds.c sds.h sdsalloc.h zmalloc.h
server.o: server.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h  ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h \
  slowlog.h  asciilogo.h
setproctitle.o: setproctitle.c
sha1.o: sha1.c solarisfixes.h sha1.h config.h
slowlog.o: slowlog.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h  ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h \
 slowlog.h
sort.o: sort.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h  ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h \
 pqsort.h
sparkline.o: sparkline.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h  ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h
syncio.o: syncio.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h  ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h
t_hash.o: t_hash.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h  ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h
t_list.o: t_list.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h  ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h
t_set.o: t_set.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h  ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h
t_string.o: t_string.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h  ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h
t_zset.o: t_zset.c server.h fmacros.h config.h solarisfixes.h \
 ../deps/lua/src/lua.h ../deps/lua/src/luaconf.h ae.h sds.h dict.h \
 adlist.h zmalloc.h  ziplist.h intset.h version.h util.h latency.h \
 sparkline.h quicklist.h zipmap.h sha1.h endianconv.h crc64.h  rio.h
util.o: util.c fmacros.h util.h sds.h sha1.h
ziplist.o: ziplist.c zmalloc.h util.h sds.h ziplist.h endianconv.h \
 config.h redisassert.h
zipmap.o: zipmap.c zmalloc.h endianconv.h config.h
zmalloc.o: zmalloc.c config.h zmalloc.h
